"""add version and priority to tasks

Revision ID: d72a2e731191
Revises: 2b8ead36b0a0
Create Date: 2026-07-11 13:07:20.594163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72a2e731191'
down_revision: Union[str, Sequence[str], None] = '2b8ead36b0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=50), server_default='medium', nullable=False))
    op.add_column('tasks', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'version')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
